### ISSUE TITLE
Support Operating system-agnostic version

### ISSUE THREAD

**Issue by yehuda-alon** [Mastercard/client-encryption-csharp#13]
The current implementation is relying on the underlying operating system to extract and use keys from X509 certificates.
With the expanding popularity of serverless deployment, it would be nice to have an Operating system-agnostic version.

My advice would be to extend the library and enable encryption / decryption based on public/private keys (not only an X509 certificate) in the FieldLevelEncryptionConfigBuilder.

The user can provide the keys in a custom way, without the need to use operation system services.

**Comment by danny-gallagher** [comment]
Hi @yehuda-alon, Thanks for your question.
When passing keys to the FieldLevelEncryptionConfigBuilder, it's completely down to the user's preference how they wish to load these keys. We do provide some example functions in the ```EncryptionUtils.cs``` class that can be used to load the keys from the file system, however it's not compulsory that these functions be used.
We don't believe it makes sense to incorporate the requested change, and will leave it to the user to decide on how keys are loaded.
