### ISSUE TITLE
[BUG] Error 400! Request is not encrypted. Payload is already encrypted

### ISSUE THREAD

**Issue by jecsoncaracut** [Mastercard/client-encryption-csharp#14]
Hello! @latompa @swaj @jkenn99 @DRuggeri  I'm encountering this error, payload is already encrypted.
Error 400 status code
{"Errors":{"Error":[{"Source":"VALIDATION_ERROR","ReasonCode":"ENCRYPTION_ERROR","Description":"-3001","Recoverable":false,"Details":"Request is not encrypted"}]}}

**Expected behavior**
Should return 200 status code.

**Screenshots**
Payload encryption
![image](https://user-images.githubusercontent.com/102776802/197673107-3cdf0e4b-1468-4220-a339-f3a38d27499b.png)
Http request
![image](https://user-images.githubusercontent.com/102776802/197672914-b56646b4-cec5-448c-bb40-1512dee1419f.png)

**Additional context**
Encrypted payload
 {
  "path": {
    "to": {
      "encryptedFoo": {
        "encryptedValue": "81316b9d66dccded47c9f9bfdb06a9591304c3cc6be4cd69c9723b5083de4cc00e3a55575a2071cb0fd7db2d2038aad6e2a507175e69e740a66cf312a23d06b467bb2d53ea3ec718bab674eeb9a17ec1df929cdb507d5448477495b6ff2c9aa23f47fab0f36e3ab82ce9c3703d4847335ce6300105b8c9328df52c5c623a149869b5a9f020698cda0fa594bd7848a7fac713699f394237ad346424e1d7c659fa19f8e5d7feaeefd0d4e7681de08a3a5b3462910ae30048ad38bfcdb5996570795d53e9675d1d53f45ebd726432fbc93778045636004bdfb69cdebb8728f4ce1e47bb68163fc81d4c634ad9d6eb04934dd7cdc47b66f1f2fdc03ad7b9c64bcd9e65b9a41e8d2749eb1ba59774cf4688ece71c3687091aed35a6b5f24f574f9e7d07670e56bdfd407c543c8ef563813fe19f2f476b6a4e51be1519eb4098a7f3f9754f2b31fa7e8af7a0f923110f8a0bf0642da8b5ee88f3b0d51c28855e626b70d1e281a7ab47d9aa530f8597df6c9b7432c6205b9b7b3e0f76fc5b112984d7b1c4dbc786bf5813693f82b77c7c025e00cf38fb73e7d635e5c49b632625583b59308479badfc014b3886221f500cd3d0f7f39a0bdc3fe8824453351ebe87161ca6f7fd86619cf8bc8cb541df0d6f4025217747b84ff98d7cb90b4ee3529b72db1",
        "iv": "bf5ec87ae3710845f361171b1c2dab94",
        "encryptedKey": "6923dd05261923c386ca1b74f00f9ee22009c19ce60e01aaa9c1c1b40203b823fba9aab8159598afdf37e3f740eb4cf89f58e3401013ab45bf7e96101a94eeb77c436b136b05c967deab976de6b936e7c023ed0e67f4703c017664c22fab5c755b0ec1ef509a4814062e86f9bca2e41ff2d369e54e4f5912e3adc44b7d9d99d50565d13dca580625a56a332a8080237993747870b1e10aba3bf1e014487ac6f0b8466f012ac16b04c97e2c79b060e4c60ffc89a0a03788ee023298bc3e84b35480289cf553dd835c0310a43e28f918063786882b3aae78182687fea4610d36692a991c26d29653fd4dda5bfb7eb3e024d5fdb295cd554e470d671c299f53cc7f"
      }
    }
  }
}

**Comment by latompa** [comment]
@jecsoncaracut It sounds like those example paths in the README `(path.to.foo...)` etc aren't the ones Mastercard expects.

Instead, check out the [examples here](https://developer.mastercard.com/mdes-digital-enablement/documentation/api-reference/#encrypting-the-request-payload). (You need a mastercard developer account for that.)

If you look in there, see how that payload example has a `encryptedPayload.encryptedData` format and a corresponding `.withEncryptionPath("$.encryptedPayload.encryptedData", "$.encryptedPayload")`.

Try using that format, see if that error goes away.

side note: maybe your example is meant to obfuscate some details, but it looks like your payload is concatenating itself, 
`payload = ... + payload + ...`, that won't work right?

**Comment by jecsoncaracut** [comment]
Hello sir @latompa I already changed the payload to this format and use the configuration you suggested above before encryption.

![image](https://user-images.githubusercontent.com/102776802/197927410-129018fb-9079-426b-b2be-ab0630639646.png)

![tempsnip](https://user-images.githubusercontent.com/102776802/197926799-19629234-341e-4aaa-9087-b767f23c4806.png)

After encryption:

{
  "encryptedPayload": {
    "encryptedData": "c023959c51c0f26814a81a4be74b6ef33afd57bfbfe3deeb445bba468113910fa28e52e79681518627f07bb711e80e0f3e86e5f7c0f3dc17c27c0c23799b149deb65d99959f631f251d3210d5d4d8d8f97457295a0b38c8176c56e7feefc6b14df9f27bb33379b1b49df10d85987b9f0395a63a370b41dee1dc1a3db7e1b55eb7d236405e24c9ed47d523b15bf4fe71d0462b4b46e0f29c915eb3e7a0e56266474b43f2cb44f9f6ba0eee72991abb2b8f5816542c014aa31a414d18842bec741fe1d903b45b0823d1ee720acff727b76e074ab3161262de40f30b32db2e398a43c2d3d23a6a9e41b2d591733c894c4536823781772d52dc995ad72366ba45524543f9e30c44aaa226d2bcf0492bb282910b6f47f6c25d939d69893ee7c59c0729c14c28972a2f96d4bc1df415e54c3379bbfcf721b1beb7e7645ad6a6fdbd82aa1fad04522f30813b11e38c1a21fabbc1e976c51b37b644d5e11931d7cb9e4246a4daded8b6241fa05e165704cecc67a4f19ec539c335ffdfafb28887f97bb1fd1bab50506494b21dabc7355f4a355747bac5b71d50ed7b212732287cb85948d045746d06c3574b1407af94a9ea6ea72c5bbb3aca60a9ba4dccd5f7ec1bb8342cdc8aa7d3e7167802ee6b1302db6b7bc98cd9469b941d780b714431fb3edc861",
    "iv": "7e5fe8826908076944ced3264d272cc8",
    "encryptedKey": "3bc5658de6b49f5d416ac0ec304ecd98427f42848df7a818985a3e9d2de5f1d8e33ead3cb9951a86a58cc591a353f392cf47f5a5da7f092791f6e67a3ed0a80fc70338646583fff22f91bfff0ecd1b0f585b3fe42d8ede8e334ab593bfacf9a485da40e9fdbb2e9643b51bf180744b512a4383dd12be05fe8f70457defab974b35fb84a03aec51251be3efeea3d0aa7824cfe55257a4ce7591192a03d2b5f913d67975a06dc28008b263448ceddaa845316c882fe9e426edf503fd8161cbb0ffae16bdfddb630af385f89ad33aea298d4c4d901b07c78e1c3e395bc68ff10f3a166b7d8f5645d3693bf15836a8e56ed00f9e9aafc88f92e096d16500aca8bf24",
    "publicKeyFingerprint": "83c52298d5ec3c75420e5828b99da10f60e952484899e6fa4062386883fb9938",
    "oaepHashingAlgorithm": "SHA512"
  }
}

I'm encountering "Failed to decode and unwrap the provided secret key value!" during decryption also.

Btw, I'm using Pay with Rewards Post Authorization API (POST Request)
Thanks for your assistance.

**Comment by kaushaltailor** [comment]
> Hello sir @latompa I already changed the payload to this format and use the configuration you suggested above before encryption.
> 
> ![image](https://user-images.githubusercontent.com/102776802/197927410-129018fb-9079-426b-b2be-ab0630639646.png)
> 
> ![tempsnip](https://user-images.githubusercontent.com/102776802/197926799-19629234-341e-4aaa-9087-b767f23c4806.png)
> 
> After encryption:
> 
> { "encryptedPayload": { "encryptedData": "c023959c51c0f26814a81a4be74b6ef33afd57bfbfe3deeb445bba468113910fa28e52e79681518627f07bb711e80e0f3e86e5f7c0f3dc17c27c0c23799b149deb65d99959f631f251d3210d5d4d8d8f97457295a0b38c8176c56e7feefc6b14df9f27bb33379b1b49df10d85987b9f0395a63a370b41dee1dc1a3db7e1b55eb7d236405e24c9ed47d523b15bf4fe71d0462b4b46e0f29c915eb3e7a0e56266474b43f2cb44f9f6ba0eee72991abb2b8f5816542c014aa31a414d18842bec741fe1d903b45b0823d1ee720acff727b76e074ab3161262de40f30b32db2e398a43c2d3d23a6a9e41b2d591733c894c4536823781772d52dc995ad72366ba45524543f9e30c44aaa226d2bcf0492bb282910b6f47f6c25d939d69893ee7c59c0729c14c28972a2f96d4bc1df415e54c3379bbfcf721b1beb7e7645ad6a6fdbd82aa1fad04522f30813b11e38c1a21fabbc1e976c51b37b644d5e11931d7cb9e4246a4daded8b6241fa05e165704cecc67a4f19ec539c335ffdfafb28887f97bb1fd1bab50506494b21dabc7355f4a355747bac5b71d50ed7b212732287cb85948d045746d06c3574b1407af94a9ea6ea72c5bbb3aca60a9ba4dccd5f7ec1bb8342cdc8aa7d3e7167802ee6b1302db6b7bc98cd9469b941d780b714431fb3edc861", "iv": "7e5fe8826908076944ced3264d272cc8", "encryptedKey": "3bc5658de6b49f5d416ac0ec304ecd98427f42848df7a818985a3e9d2de5f1d8e33ead3cb9951a86a58cc591a353f392cf47f5a5da7f092791f6e67a3ed0a80fc70338646583fff22f91bfff0ecd1b0f585b3fe42d8ede8e334ab593bfacf9a485da40e9fdbb2e9643b51bf180744b512a4383dd12be05fe8f70457defab974b35fb84a03aec51251be3efeea3d0aa7824cfe55257a4ce7591192a03d2b5f913d67975a06dc28008b263448ceddaa845316c882fe9e426edf503fd8161cbb0ffae16bdfddb630af385f89ad33aea298d4c4d901b07c78e1c3e395bc68ff10f3a166b7d8f5645d3693bf15836a8e56ed00f9e9aafc88f92e096d16500aca8bf24", "publicKeyFingerprint": "83c52298d5ec3c75420e5828b99da10f60e952484899e6fa4062386883fb9938", "oaepHashingAlgorithm": "SHA512" } }
> 
> I'm encountering "Failed to decode and unwrap the provided secret key value!" during decryption also using same config.
> 
> I'm getting this response error message {"Errors":{"Error":[{"Source":"authorizations-rest-api","ReasonCode":"Unauthorized","Description":"Failed to authenticate request for /error","Recoverable":false,"Details":""}]}} which I think should not the exact error message since I don't have problem with OAuth .
> 
> Btw, I'm using Pay with Rewards Post Authorization API (POST Request) Sandbox Thanks for your assistance.

@jecsoncaracut - You will need to use JWE Encryption as mentioned in the document - 
https://developer.mastercard.com/pay-with-rewards/documentation/api-basics/securing-sensitive-data/#configuring-jwe-instance-to-encrypt-and-decrypt-entire-payload

**Comment by danny-gallagher** [comment]
Closing issue
