### ISSUE TITLE
[BUG] JWE for .net framework

### ISSUE THREAD

**Issue by madanstc** [Mastercard/client-encryption-csharp#19]
**Description**

When using this plugin in .net framework 4.8 it gives an error.

AES/GCM/NoPadding is unsupported on .NET Standard < 2.1

**To Reproduce**

JweEncryption.encryptPayload(requestPayload, config);

**Expected behavior**

encryption should work as this plugin is targeting less than 2.1

**Comment by danny-gallagher** [comment]
Hi @madanstc,

Thanks for creating this issue. You can see the condition which throws this error here: https://github.com/Mastercard/client-encryption-csharp/blob/main/Mastercard.Developer.ClientEncryption.Core/Encryption/AES/AesGcm.cs#L52

Unfortunately the type of AESGCM encryption we use in this library cannot be used with .NET Standard < 2.1.
If you have any recommendations to update this library we'd be happy to have look at a PR.
