### ISSUE TITLE
[BUG] RestSharpEncryptionInterceptor version difference between package and source code

### ISSUE THREAD

**Issue by alppaycore** [Mastercard/client-encryption-csharp#23]
I am using 1.7.0 version of nuget package and getting an error (method not found) in RestSharpEncryptionInterceptor. I checked the source code there is no problem in same line. 

![image](https://github.com/Mastercard/client-encryption-csharp/assets/153804853/671a2983-cf79-4b63-a5e0-735687067899)

![image](https://github.com/Mastercard/client-encryption-csharp/assets/153804853/b872c7c1-8da5-4eb4-852f-9e78c5f0961c)

![image](https://github.com/Mastercard/client-encryption-csharp/assets/153804853/53bf3beb-6113-4a24-9b2a-f6eef6bf0a86)

**Comment by danny-gallagher** [comment]
Hi @alppaycore, Thanks for raising this issue!
This could be a result of conflicting versions of Restsharp on your local machine. Our library uses version 108.0.3 of Restsharp.
If aligning these versions of Restsharp on your local machine doesn't work, please provide with code snippets that we can use to further debug the issue you're experiencing.

**Comment by alppaycore** [comment]
Hi,

I'm trying to integrate with mdes customer service. I created the client project from the file below with openapi :
https://static.developer.mastercard.com/content/mdes-customer-service/swagger/mdes-customer-service.yaml
As you said, I changed the version of the RestSharp library to 108.0.3. This time, the generated client code is not compiled.
The project is attached.

Best Regards,


Alp Kamil Sargıh
Corporate Software Architect 

PayCore | E: ***@***.***
T: +90 212 328 3331 | M:

**Comment by karen-avetisyan-mc** [comment]
Hi @alppaycore 
I do not see the attached project, can you please attached to this GitHub issue #23 directly 

Thanks
Karen

**Comment by alppaycore** [comment]
https://github.com/alppaycore/MastercardApi.Client

**Comment by karen-avetisyan-mc** [comment]
Hi @alppaycore 
I was able to build your project, after I have run the following command
`dotnet add package RestSharp`.
Please read here for more reference: https://restsharp.dev/intro.html#introduction.
Let me know if it helps

**Comment by alppaycore** [comment]
It compiles with the current Resharp version (110.2.0), there is no problem there. I get an error when I run it. I cannot compile it with version 108.0.3 either.

**Comment by karen-avetisyan-mc** [comment]
@alppaycore can you please regeneration the client using https://github.com/openapitools/openapi-generator.git version [v6.6.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v6.6.0).
The generated code you have provided is using the version 7 which in fact using Restsgarp 110.2.3 - and those are incompatible. Our library does support 108.0.3 - and we are moving to next version soon.
let me know if that will work for you.

**Comment by alppaycore** [comment]
I tried it with version 6.6.0, it worked. Thanks.

**Comment by karen-avetisyan-mc** [comment]
Closing the issue. the resolution is to use https://github.com/openapitools/openapi-generator.git version [v6.6.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v6.6.0).
