### ISSUE TITLE
[BUG] Umaut Characters not supported

### ISSUE THREAD

**Issue by Biggo89** [Mastercard/client-encryption-csharp#29]
#### Bug Report Checklist

- [ ] Have you provided a code sample to reproduce the issue?
- [x] Have you tested with the latest release to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

**Description**
German Character not supported due to ASCII encoding

**To Reproduce**
Encrypt any payload with umlauts characters then the decrypted one is with a question mark in place of umlaut

**Comment by karen-avetisyan-mc** [comment]
Hi, 
In this library - we do not provide any other languages, except English.
Sorry
Karen

**Comment by karen-avetisyan-mc** [comment]
However I would like to review the PR and check if it is working fine. Lets take the discussion on PR review.

**Comment by karen-avetisyan-mc** [comment]
Version 1.9.1  has been published: https://www.nuget.org/packages/Mastercard.Developer.ClientEncryption.Core/
@Biggo89 FYI
