### ISSUE TITLE
[REQ] Moving back to .NetStandard2.0 for backward compatibility

### ISSUE THREAD

**Issue by Biggo89** [Mastercard/client-encryption-csharp#32]
### Not able to use the latest version with .net Full Framework 4.8.

the latest version of the lib, with the fix related to the umlaut characters, is not compatible with .net Framework 4.8 

### Describe the solution you'd like

Can you move back to .net Standard 2.0 that sill support .net Framework 4.8?

**Comment by karen-avetisyan-mc** [comment]
Hi @Biggo89 

What I can suggest is for you to create fork from release 1.8.0 - https://github.com/Mastercard/client-encryption-csharp/tree/v1.8.0 and merge your changes there. I will create 1.8.1 release for you to have it 
let me know i that works for you.

We have no plans to move our library to netstandard 2.0.
Thanks
Karen

**Comment by ShimonaR-MC** [comment]
Please see the comment above.
