### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by AGHns** [Mastercard/client-encryption-csharp#6]
#### Bug Report Checklist

- [ ] Have you provided a code sample to reproduce the issue?
- [x] Have you tested with the latest release to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

**Description**
A clear and concise description of what is the question, suggestion, or issue and why this is a problem for you.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (OS, language version, etc..).

**Related issues/PRs**
Has a similar issue/PR been reported/opened before?

**Suggest a fix/enhancement**
If you can't fix the bug yourself, perhaps you can point to what might be causing the problem (line of code or commit), or simply make a suggestion.

*If this is a Feature request, please check out [this](feature_request.md).*

**Comment by AGHns** [comment]
Please find  the attached related error pn
![Mastercard_clientencryption_Cofigration_v1 3_pass](https://user-images.githubusercontent.com/104240828/164884726-eaca6083-fc6b-4679-bd6f-a05a8b88a539.png)
![with_mastercard_clientencryption_core_v1 3](https://user-images.githubusercontent.com/104240828/164884728-afd04867-55fd-4742-928b-de8961fe5a41.png)
![download_nuget_netstandardref_to_get_netstandardv21_error](https://user-images.githubusercontent.com/104240828/164884729-99ab2590-53d7-4923-ae41-5126db6e4873.png)
![Mastercard_client_encryption_core_v2_before_cofigalso](https://user-images.githubusercontent.com/104240828/164884731-74a13aac-1ae5-44f4-97d8-475b9c8ba942.png)
g

**Comment by jaaufauvre** [comment]
@AGHns, 

We don't accept bug reports without proper title and description.

Thanks for your understanding,
