### ISSUE TITLE
Missing netstandard.dll correct version 

### ISSUE THREAD

**Issue by AGHns** [Mastercard/client-encryption-csharp#7]
Our project use framework 4.7.1 and we are using C# coding
I try use both MasterCard client encryption “core”  DLL downloaded from NuGet

Version 1.3 unfortunately when I reach to the encryption “payload” I got an error that zero padding not supported with version <2.0
Version 2 , when am trying to set the configuration an exception raised directly “netstandard dll version conflict” I try to download this dll with v2.1 but I couldn’t get it😢
how can I solve this problem
Pleas help m
![with_mastercard_clientencryption_core_v1 3](https://user-images.githubusercontent.com/104240828/165145702-f55a3b12-e2c6-4141-a384-cc7e10db7841.png)
![download_nuget_netstandardref_to_get_netstandardv21_error](https://user-images.githubusercontent.com/104240828/165145709-aca67a59-0973-4068-a841-5b67b925950a.png)
![Mastercard_client_encryption_core_v2_before_cofigalso](https://user-images.githubusercontent.com/104240828/165145711-5e891d1e-3418-4265-ad31-eb86a2da6eff.png)
![Mastercard_clientencryption_Cofigration_v1 3_pass](https://user-images.githubusercontent.com/104240828/165145714-185043eb-41df-49ab-a4a2-64dbe1e04559.png)
e

**Comment by jaaufauvre** [comment]
Hi @AGHns,

AES-GCM isn't available in .NET Framework 4.x (it was introduced with .NET Standard 2.1 and .NET Core 3.0). 

See also:  https://dotnet.microsoft.com/en-us/platform/dotnet-standard#versions.

This explains the behaviour you observe:

1. "_AES/GCM/NoPadding is unsupported on .NET Standard < 2.1_" is raised when the target framework (in this case .NET 4.7.1 legacy) doesn't implement .NET Standard 2.1 APIs.

2. "_Package {x} has a package type that is not supported by project {y}_" means you're trying to use the `netstandard2.1` version of  [`ClientEncryption.Core`](https://www.nuget.org/packages/Mastercard.Developer.ClientEncryption.Core/) with a project targeting a framework that isn't compatible.

That being said, you have the following options:
* Use .NET Core (if possible). .NET 6.0 is the way to go for new projects.
* Fork this project, and leverage a .NET package like Bouncy Castle. More information here: https://www.scottbrady91.com/c-sharp/aes-gcm-dotnet.

I hope this helps!
